import { img } from "../utils/getImageUrl";

const projectsData = [

  {
    id: 1,
    title: "Trippy",
    subtitle: "React",
    img: img("trippy.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/trippy1/",
    github: "https://github.com/ghiathmousa-arch/trippy1",
    date: "30-1-2026",
    description: "A travel website built with React and React Router. Features multiple pages including Home, About, Service, Contact, and Login with a responsive navbar and mobile menu.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: ["React"],
    libraries: ["React Icons", "React Router DOM", "Lucide React"],
  },

  {
    id: 2,
    title: "Dashboard",
    subtitle: "React",
    img: img("Dashbord.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Dashboard/",
    github: "https://github.com/ghiathmousa-arch/Dashboard",
    date: "20-3-2026",
    description: "A responsive admin dashboard built with React, connected to a Laravel API. Supports full CRUD operations with a clean and modern UI.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: ["React"],
    libraries: ["React Icons", "React Router DOM"],
  },

  {
    id: 3,
    title: "Blog Posts",
    subtitle: "Html Css javascript React",
    img: img("blog.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Blog-Posts/",
    github: "https://github.com/ghiathmousa-arch/Blog-Posts",
    date: "10-1-2026",
    description: "A responsive blog website built with HTML, CSS3, JavaScript, and React. Features a newsletter subscription, dynamic blog post grid, and login/signup pages with a clean modern layout.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },

  {
    id: 4,
    title: "Learning Platform",
    subtitle: "Html - Css",
    img: img("platform.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Learning-platform/",
    github: "https://github.com/ghiathmousa-arch/Learning-platform",
    date: "28-12-2025",
    description: "A fully responsive educational platform built with HTML & CSS. Features multiple pages including courses, blog, FAQs, contact, and login. Clean layout with category browsing and course listings.",
    languages: ["Html5", "Css3"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 5,
    title: "Cozy Shop",
    subtitle: "Html-Css3-Vanilla javascript",
    img: img("cozy.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/cozy-shop/",
    github: "https://github.com/ghiathmousa-arch/cozy-shop",
    date: "29-12-2025",
    description: "Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 6,
    title: "Flora",
    subtitle: "Html - Css",
    img: img("flora.png"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Flora/",
    github: "https://github.com/ghiathmousa-arch/Flora",
    date: "1-12-2025",
    description: "A responsive real estate website built with HTML & CSS. Displays available properties with filtering by location, price, and type. Includes trending properties and best deals sections.",
    languages: ["Html5", "Css3"],
    frameworks: [],
    libraries: [],
  },
];

export default projectsData;
