const projectsData = [
  {
    id: 1,
    title: "Learning platform",
    subtitle: "Html-Css",
    img: "/platform.png",
    icon: "/card.png",
    demo: "https://ghiathmousa-arch.github.io/Learning-platform/",
    github: "https://github.com/ghiathmousa-arch/Learning-platform",
    date: "12-5-2024",
    description: "Lorem ipsum dolor sit amet consectetur. Tristique amet sed massa nibh lectus netus in. Aliquet donec morbi convallis pretium. Turpis tempus pharetra Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 2,
    title: "Flora",
    subtitle: "Html-Css",
    img: "/flora.png",
    icon: "/card.png",
    demo: "https://ghiathmousa-arch.github.io/Flora/",
    github: "https://github.com/ghiathmousa-arch/Flora",
    date: "1-11-2025",
    description: "Lorem ipsum dolor sit amet consectetur. Tristique amet sed massa nibh lectus netus in.",
    languages: ["Html5", "Css3"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 3,
    title: "Blog Posts",
    subtitle: "Html-Css3-Vanilla javascript",
    img: "/blog.png",
    icon: "/card.png",
    demo: "https://ghiathmousa-arch.github.io/Blog-Posts/",
    github: "https://github.com/ghiathmousa-arch/Blog-Posts",
    date: "1-1-2024",
    description: "Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 4,
    title: "Dashboard",
    subtitle: "React",
    img: "/Dashbord.png",
    icon: "/card.png",
    demo: "#",
    github: "#",
    date: "1-1-2024",
    description: "Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: ["React"],
    libraries: [],
  },
  {
    id: 5,
    title: "Educational Platform",
    subtitle: "Html-Css3-Vanilla javascript",
    img: "/Image.png",
    icon: "/card.png",
    demo: "#",
    github: "#",
    date: "1-1-2024",
    description: "Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 6,
    title: "Educational Platform",
    subtitle: "Html-Css3-Vanilla javascript",
    img: "/Image.png",
    icon: "/card.png",
    demo: "#",
    github: "#",
    date: "1-1-2024",
    description: "Lorem ipsum dolor sit amet consectetur.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },
];

export default projectsData;