import { img } from "../utils/getImageUrl";

const projectsData = [

  // ملاحظة: الترتيب هون هو ترتيب العرض بالموقع.
  // الـ id مستقل عن الترتيب عشان روابط /projects/:id القديمة ما تنكسر.

  {
    id: 7,
    title: "Real Estate Platform",
    tag: "Team Project — Real Client",
    featured: true,
    subtitle: "React · Node.js · MongoDB",
    img: img("realestate.jpg"),
    icon: img("card.png"),
    demo: "https://real-state-six-chi.vercel.app",
    github: null,
    description: "منصة عقارية بتساعد الزوار يلاقوا العقار المناسب بسهولة، عن طريق بحث وفلترة متقدمة ومعلومات موثوقة عن كل عقار.",
    tech: ["React", "Node.js", "MongoDB"],
  },

  {
    id: 8,
    title: "MediLink",
    tag: "Graduation Project (2026)",
    subtitle: "Next.js · TypeScript · Tailwind CSS · PostgreSQL · Prisma",
    img: img("medilink.jpg"),
    icon: img("card.png"),
    demo: "https://medilink-omega-murex.vercel.app",
    github: "https://github.com/ghiathmousa-arch/MediLink",
    description: "نظام يجمع الملف الصحي الكامل للمريض بمكان واحد، وبينبّه تلقائياً لو في تعارض بين الأدوية أو حساسية عند المريض.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL", "Prisma"],
  },

  {
    id: 9,
    title: "LearnWise",
    tag: "Graduation Project (2026)",
    subtitle: "Next.js · TypeScript · React · Python · FastAPI",
    img: img("learnwise.jpg"),
    icon: img("card.png"),
    demo: "https://learnwise-six.vercel.app",
    github: "https://github.com/ghiathmousa-arch/learnwise",
    description: "منصة بتقترح على المستخدم محتوى تعليمي مشابه لاهتماماته بذكاء، وبتدعم البحث بالعربي والإنجليزي مع بعض.",
    tech: ["Next.js", "TypeScript", "React", "Python", "FastAPI"],
  },

  {
    id: 10,
    title: "RxChef",
    tag: "Graduation Project",
    subtitle: "Next.js · TypeScript · FastAPI · PostgreSQL · XGBoost",
    img: img("rxchef.jpg"),
    icon: img("card.png"),
    demo: "https://rx-chef.vercel.app",
    github: "https://github.com/ghiathmousa-arch/RxChef",
    description: "نظام بيتحقق من وجود تعارض خطير بين دوائين قبل ما ياخدهم المستخدم مع بعض، وبيقترح بدائل آمنة بمكانهم.",
    tech: ["Next.js", "TypeScript", "FastAPI", "PostgreSQL", "XGBoost"],
  },

  {
    id: 11,
    title: "Vehicle Platform",
    tag: "Personal Project — Solo Full-stack",
    subtitle: "Next.js · TypeScript · PostgreSQL · Prisma",
    img: img("vehicle.jpg"),
    icon: img("card.png"),
    demo: "https://vehicle-platform-six.vercel.app",
    github: "https://github.com/ghiathmousa-arch/vehicle-platform",
    description: "منصة بتخلي أي حدا يستعلم عن بيانات مركبة برقم اللوحة بسهولة، ومعها لوحة تحكم إدارية كاملة لإدارة البيانات.",
    tech: ["Next.js", "TypeScript", "PostgreSQL", "Prisma"],
  },

  {
    id: 1,
    title: "Trippy",
    subtitle: "React",
    img: img("trippy.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/trippy1/",
    github: "https://github.com/ghiathmousa-arch/trippy1",
    date: "30-1-2026",
    description: "A travel website built with React and React Router. Features multiple pages including Home, About, Service, Contact, and Login with a responsive navbar and mobile menu.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: ["React"],
    libraries: ["React Icons", "React Router DOM", "Lucide React"],
  },

  {
    id: 2,
    title: "Dashboard",
    subtitle: "React",
    img: img("Dashbord.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Dashboard/",
    github: "https://github.com/ghiathmousa-arch/Dashboard",
    date: "20-3-2026",
    description: "A responsive admin dashboard built with React, connected to a Laravel API. Supports full CRUD operations with a clean and modern UI.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: ["React"],
    libraries: ["React Icons", "React Router DOM"],
  },

  {
    id: 3,
    title: "Blog Posts",
    subtitle: "Html Css javascript React",
    img: img("blog.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Blog-Posts/",
    github: "https://github.com/ghiathmousa-arch/Blog-Posts",
    date: "10-1-2026",
    description: "A responsive blog website built with HTML, CSS3, JavaScript, and React. Features a newsletter subscription, dynamic blog post grid, and login/signup pages with a clean modern layout.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },

  {
    id: 4,
    title: "Learning Platform",
    subtitle: "Html - Css",
    img: img("platform.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Learning-platform/",
    github: "https://github.com/ghiathmousa-arch/Learning-platform",
    date: "28-12-2025",
    description: "A fully responsive educational platform built with HTML & CSS. Features multiple pages including courses, blog, FAQs, contact, and login. Clean layout with category browsing and course listings.",
    languages: ["Html5", "Css3"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 5,
    title: "Cozy Shop",
    subtitle: "Html-Css3-Vanilla javascript",
    img: img("cozy.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/cozy-shop/",
    github: "https://github.com/ghiathmousa-arch/cozy-shop",
    date: "29-12-2025",
    description: "A responsive online shop built with HTML, CSS3, and vanilla JavaScript. Features a product catalog, category filtering, and a cart interaction built without any framework.",
    languages: ["Html5", "Css3", "Javascript"],
    frameworks: [],
    libraries: [],
  },
  {
    id: 6,
    title: "Flora",
    subtitle: "Html - Css",
    img: img("flora.jpg"),
    icon: img("card.png"),
    demo: "https://ghiathmousa-arch.github.io/Flora/",
    github: "https://github.com/ghiathmousa-arch/Flora",
    date: "1-12-2025",
    description: "A responsive real estate website built with HTML & CSS. Displays available properties with filtering by location, price, and type. Includes trending properties and best deals sections.",
    languages: ["Html5", "Css3"],
    frameworks: [],
    libraries: [],
  },
];

export default projectsData;
